# Generated by Django 4.1.1 on 2023-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_interviewscheduling_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewscheduling',
            name='interviewlink',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
