# Generated by Django 4.2.5 on 2024-01-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
