# Generated by Django 4.2.5 on 2024-02-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_interdetails_internship_classdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interndetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=50)),
                ('stipend', models.CharField(max_length=50)),
                ('whocanapply', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='classdetails',
            name='candi_id',
        ),
        migrations.RemoveField(
            model_name='classdetails',
            name='inter_id',
        ),
        migrations.DeleteModel(
            name='interdetails',
        ),
        migrations.DeleteModel(
            name='classdetails',
        ),
        migrations.DeleteModel(
            name='internship',
        ),
    ]
