# Generated by Django 4.2.5 on 2024-02-12 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_interndetails_lastdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interndetails',
            name='lastdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interndetails',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interndetails',
            name='whocanapply',
            field=models.CharField(default='Anyone', max_length=100),
        ),
    ]
