# Generated by Django 4.2.5 on 2024-02-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_resumeschema_payementdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
