# Generated by Django 4.2.5 on 2024-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_candidateskillsandtechnologies_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='jobseeker_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
