# Generated by Django 4.2.5 on 2024-02-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_jobseekerprofile_jobseeker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='skill_name',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='jobseeker_id',
        ),
    ]
