# Generated by Django 4.2.5 on 2024-02-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_jobseekerprofile_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experience',
        ),
    ]
