# Generated by Django 4.2.5 on 2023-10-04 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_payementdetails_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeschema',
            name='jprofile',
        ),
        migrations.RemoveField(
            model_name='employeerprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='employeerprofile',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='expected_salary',
        ),
        migrations.DeleteModel(
            name='Interviewscheduling',
        ),
        migrations.DeleteModel(
            name='ResumeSchema',
        ),
    ]
