# Generated by Django 4.2.5 on 2023-10-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_resumeschema_jprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='highestqualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
