# Generated by Django 4.2.5 on 2024-01-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_jobseekerprofile_highestqualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewscheduling',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_type', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_timeanddate', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=0, verbose_name='status')),
                ('message', models.TextField(blank=True, max_length=255, null=True)),
                ('interviewlink', models.URLField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.jobapplicationdetails')),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.jobdetails')),
            ],
        ),
    ]
