# Generated by Django 4.2.5 on 2024-01-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('feedback', models.TextField(null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('good', models.BooleanField(default=True, verbose_name='good')),
                ('bad', models.BooleanField(default=True, verbose_name='bad')),
                ('neutral', models.BooleanField(default=True, verbose_name='neutral')),
                ('rating', models.CharField(max_length=100, null=True)),
                ('can_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.question')),
            ],
        ),
    ]
