# Generated by Django 4.2.5 on 2024-01-30 04:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='interdetails',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('interns', models.CharField(max_length=100, null=True)),
                ('internname', models.CharField(max_length=100, null=True)),
                ('interndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='internship',
            fields=[
                ('intern_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('title', models.CharField(max_length=100, null=True)),
                ('durno', models.IntegerField(blank=True, null=True)),
                ('durex', models.CharField(max_length=100, null=True)),
                ('stdate', models.DateField()),
                ('enddate', models.DateField()),
                ('caption', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('category', models.CharField(max_length=100, null=True)),
                ('stipend', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('moreinfo', models.TextField(null=True)),
                ('whoapply', models.TextField(null=True)),
                ('onoff', models.CharField(max_length=100, null=True)),
                ('certificate', models.BooleanField(default=True, verbose_name='status')),
                ('tim', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classdetails',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('interndate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('interntimes', models.CharField(default=0, max_length=100, null=True)),
                ('candi_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inter_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.internship')),
            ],
        ),
    ]
