# Generated by Django 4.2.5 on 2024-02-06 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_interndetails_remove_classdetails_candi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interndetails',
            name='lastdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interndetails',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
