# Generated by Django 4.2.5 on 2024-02-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_interndetails_lastdate_alter_interndetails_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interndetails',
            name='lastdate',
        ),
        migrations.RemoveField(
            model_name='interndetails',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='interndetails',
            name='whocanapply',
        ),
    ]
