# Generated by Django 4.2.5 on 2024-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_jobseekerprofile_skills_delete_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateskillsandtechnologies',
            name='skill_name',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
