# Generated by Django 4.2.5 on 2024-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_candidateskillsandtechnologies_skill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateskillsandtechnologies',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
