# Generated by Django 4.2.5 on 2024-02-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_rename_skill_name_jobseekerprofile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
