# Generated by Django 4.2.5 on 2024-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_jobseekerprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
