# Generated by Django 4.2.5 on 2024-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_jobseekerprofile_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateskillsandtechnologies',
            name='skill_name',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skill',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
