# Generated by Django 4.2.5 on 2024-02-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_remove_candidateskillsandtechnologies_skill_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='skill',
            new_name='skills',
        ),
        migrations.AddField(
            model_name='candidateskillsandtechnologies',
            name='skill_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
