# Generated by Django 4.2.5 on 2024-04-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_remove_interndetails_stipend_jobdetails_job_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='job_location',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='office_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
