# Generated by Django 4.2.5 on 2024-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_remove_jobdetails_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interndetails',
            name='stipend',
            field=models.CharField(default='2000', max_length=50),
        ),
        migrations.AlterField(
            model_name='interndetails',
            name='whocanapply',
            field=models.CharField(default='CS related', max_length=100),
        ),
    ]
